name: Send WhatsApp Message

on:
  schedule:
    - cron: '30 10 * * *'  # 07:30 AM (Brazil time - UTC-3)
  workflow_dispatch:  # allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python main.py
