name: Send WhatsApp Message

on:
  schedule:
    - cron: '51 10 * * 1-5'  # 07:51 Brazil
    - cron: '02 11 * * 1-5'  # 08:02 Brazil
    - cron: '13 11 * * 1-5'  # 08:13 Brazil
    - cron: '24 11 * * 1-5'  # 08:24 Brazil
    - cron: '35 11 * * 1-5'  # 08:35 Brazil
    - cron: '46 11 * * 1-5'  # 08:46 Brazil
    - cron: '57 11 * * 1-5'  # 08:57 Brazil
    - cron: '08 12 * * 1-5'  # 09:08 Brazil
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python -u main.py

      # =========================
      # UPDATE STATE FILE
      # =========================

      - name: Commit state files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_sent.txt schedule.txt
          git commit -m "update state files" || echo "No changes"
          git push