name: Send WhatsApp Message

on:
  schedule:
    - cron: '55 10 * * 1-5'  # 07:55 Brazil (UTC-3)
    - cron: '15 11 * * 1-5'  # 08:15 Brazil
    - cron: '25 11 * * 1-5'  # 08:25 Brazil
    - cron: '36 11 * * 1-5'  # 08:36 Brazil
    - cron: '46 11 * * 1-5'  # 08:46 Brazil
    - cron: '56 11 * * 1-5'  # 08:56 Brazil
  workflow_dispatch:  # allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python -u main.py

      # =========================
      # UPDATE CONTROL FILE
      # =========================

      - name: Commit last sent date
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_sent.txt
          git commit -m "update last sent date" || echo "No changes"
          git push